---
- name: Show use_python3 and pip_executable
  debug:
    msg: "Use Python3: {{ use_python3 }}; Pip Exe: {{ pip_executable }}; Python Exe: {{ python_executable }}"

- name: Install NLTK
  pip:
    name: nltk
    state: present
    executable: "{{ pip_executable }}"

- name: Install NLTK Data
  shell: "{{ python_executable }} -m nltk.downloader -d {{ NLTK_DATA_DIR }} {{ item }}"
  with_items: "{{ NLTK_DATA_PACKAGE_IDS }}"
  args:
    creates: "{{ NLTK_DATA_DIR }}"
