---
- name: Install NLTK
  pip:
    name: nltk
    state: present

- name: Install NLTK Data
  shell: "python -m nltk.downloader -d {{ NLTK_DATA_DIR }} {{ item }}"
  with_items: "{{ NLTK_DATA_PACKAGE_IDS }}"
  args:
    creates: "{{ NLTK_DATA_DIR }}"
